// Regenerate src/schema.d.ts from smart-pet-backend's openapi.json.
//   OPENAPI_URL overrides the source (default: the backend's `development` branch).
import { writeFileSync } from 'node:fs';
import openapiTS, { astToString } from 'openapi-typescript';

const url =
  process.env.OPENAPI_URL ||
  'https://raw.githubusercontent.com/jubasjl76-eng/smart-pet-backend/development/openapi.json';

const ast = await openapiTS(new URL(url), { alphabetize: true });
const header = `/**
 * GENERATED by \`npm run codegen\` from ${url}
 * Do not edit. Re-run codegen when the backend's openapi.json changes.
 */
`;
writeFileSync(new URL('../src/schema.d.ts', import.meta.url), header + astToString(ast));
console.log('wrote src/schema.d.ts from', url);
